//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerMembership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomerMembership()
        {
            this.tblFitnessMeasurements = new HashSet<tblFitnessMeasurement>();
        }
    
        public int CM_ID { get; set; }
        public string MembershipNo { get; set; }
        public int CustomerID { get; set; }
        public int MT_ID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public int Months { get; set; }
        public System.DateTime DateTo { get; set; }
        public decimal ChargesPerMonth { get; set; }
        public decimal DiscountPercentage { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal VATPercentage { get; set; }
        public decimal VATAmount { get; set; }
        public decimal ServiceTAXPercentage { get; set; }
        public decimal ServiceTAXAmount { get; set; }
        public decimal TotalCharges { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal TotalPaid { get; set; }
        public decimal Balance { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblMembershipType tblMembershipType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFitnessMeasurement> tblFitnessMeasurements { get; set; }
    }
}
