//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFitnessMeasurement
    {
        public int ID { get; set; }
        public int CustomerM_ID { get; set; }
        public decimal Weight { get; set; }
        public decimal BodyFat { get; set; }
        public decimal BodyMass { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tblCustomerMembership tblCustomerMembership { get; set; }
    }
}
