//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblSoldProducts = new HashSet<tblSoldProduct>();
            this.tblStocks = new HashSet<tblStock>();
        }
    
        public int PID { get; set; }
        public string ProductNo { get; set; }
        public string ProductName { get; set; }
        public int SubCategoryID { get; set; }
        public string Category { get; set; }
        public string Features { get; set; }
        public decimal VAT { get; set; }
        public decimal ServiceTAX { get; set; }
        public decimal Discount { get; set; }
        public decimal Price { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual tblSubCategory tblSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSoldProduct> tblSoldProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStock> tblStocks { get; set; }
    }
}
