//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStock
    {
        public int StockID { get; set; }
        public string StockNo { get; set; }
        public int ProductID { get; set; }
        public int SupplierID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
        public virtual tblTemp_Stock tblTemp_Stock { get; set; }
    }
}
